### ISSUE TITLE
Cross platform build failed

### ISSUE THREAD

**Issue by elgs** [mattn/go-sqlite3#106]
When I tried to build from OS X for Linux, it says:

```
$ GOOS=linux GOARCH=amd64 go install
# github.com/mattn/go-sqlite3
../../../mattn/go-sqlite3/sqlite3.c:241 unknown #: if
../../../mattn/go-sqlite3/sqlite3.c:256 unknown #: if
../../../mattn/go-sqlite3/sqlite3.c:296 unknown #: if
../../../mattn/go-sqlite3/sqlite3.c:309 unknown #: if
../../../mattn/go-sqlite3/sqlite3.c:339 unknown #: if
../../../mattn/go-sqlite3/sqlite3.c:342 unknown #: elif
../../../mattn/go-sqlite3/sqlite3.c:343 macro redefined: SQLITE_INT_TO_PTR
../../../mattn/go-sqlite3/sqlite3.c:344 macro redefined: SQLITE_PTR_TO_INT
../../../mattn/go-sqlite3/sqlite3.c:345 unknown #: elif
../../../mattn/go-sqlite3/sqlite3.c:346 macro redefined: SQLITE_INT_TO_PTR
../../../mattn/go-sqlite3/sqlite3.c:347 macro redefined: SQLITE_PTR_TO_INT
too many errors
```

**Comment by jhcodeh** [comment]
Hi,

I would like to compile to arm on osx.
With the following command:
GOOS=linux GOARCH=arm CGO_ENABLED=1 go build -o foo main.go

I get:
# runtime/cgo
clang: error: argument unused during compilation: '-mno-thumb'

Thanks for every help :-)

**Comment by maximchick** [comment]
Hi, this is how I cross compile binary for freescale/arm on i386 architecture:

```CC=/tools/m1sdk-tiny-1.0.0/toolchain/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin/arm-linux-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm go build main.go```

**Comment by marcboeker** [comment]
Thanks!

**Comment by hit9** [comment]
I have the same problem on osx, attempting to build linux/amd64 version for my program.

```
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mattn** [comment]
try with `export CC=gcc`.

**Comment by hit9** [comment]
@mattn Hello,

```
$ CC=gcc-4.9 GOOS=linux GOARCH=amd64 CGO_ENABLED=1 godep go build                                                                                                                                                 1 ↵ (go1.5.2 node@v5.0.0)
# runtime/cgo
gcc-4.9: warning: couldn't understand kern.osversion '14.3.0
# runtime/cgo
gcc-4.9: warning: couldn't understand kern.osversion '14.3.0
# runtime/cgo
gcc-4.9: warning: couldn't understand kern.osversion '14.3.0
/Users/hit9/github/oo/go/src/runtime/cgo/cgo.go:52:19: fatal error: errno.h: No such file or directory
compilation terminated.
godep: go exit status 2
```

**Comment by mattn** [comment]
are you doing cross-compiling? when you need to use cross-compiler not host-compiler.

**Comment by hit9** [comment]
@mattn Thanks.

**Comment by bobintornado** [comment]
Having a little problem Mac OS and not sure what's the cause :/

Command used
`CGO_ENABLED=1 CC=gcc-5 GOARM=7 GOARCH=arm GOOS=linux go build`

Error countered:
````
# runtime/cgo
gcc-5: error: unrecognized command line option '-marm'
````

Any hints please?

**Comment by jeffbmartinez** [comment]
Ran into similar issue cross-compiling a linux binary on osx. Near as I can tell in my mini investigation, cross-compiling *would* work except that osx's implementation of the linker tool (`ld`) doesn't understand the `--build-id=none` flag, which is where it chokes. Both `gcc` and `clang` attempt to pass this flag along to `ld` regardless of what you do with the `CC`, `GCO_ENABLED`, etc environment variables, so it's simply not gonna work.

I have a simple work around using [docker](https://www.docker.com/) which will hopefully help others who don't want to go through the trouble of recompiling a linux version of `ld` for osx:

Note: Naturally a docker workaround will require that you have [docker](https://www.docker.com/) installed :)

@mattn If you think it's reasonable feel free to add it to your readme where it will be more visible. I can make a PR as well if you like.

    docker run --rm -v $GOPATH:/go -w /go/src/path/to/app golang:latest go build -v

This will put your executable in the expected place, in this case, /go/src/path/to/app.

You just need to update that `/go/src/path/to/app` part to be your actual directory containing your app, for example, `/go/src/path/github.com/username/awesomeSqliteApp`

If you want this working in a script like I have (for example I use a python fabric script to build and deploy automatically), you can do the following to prep docker on osx, since otherwise it requires the "Docker Quickstart Terminal":

    eval $(docker-machine env default)
    docker run --rm -v $GOPATH:/go -w /go/src/path/to/app golang:latest go build -v

In theory this should work on any platform that can run docker, though I've only tried on osx.

**Comment by mattn** [comment]
@jeffbmartinez Thanks. Using docker is one of the way to do cross-compiling. So it's useful. If possible, could you please send me pull-request to update README.md?

**Comment by cprevallet** [comment]
Leaving this comment in the hopes it helps someone else in 2016.

Cross compiling Linux (Debian Jessie amd64) -> Windows (amd64) and OSX (amd64) worked for me with the following:

To Windows:  
apt-get install gcc_mingw64
env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build $appname

To OSX:  
Follow instructions at https://github.com/tpoechtrager/osxcross to build apple cross compiler
env CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC=o64-clang go build $appname

**Comment by oldfeel** [comment]
@cprevallet Thank you, ubuntu is work.

`apt-get install gcc-mingw-w64`

**Comment by ikkemaniac** [comment]
for documentation purposes:
in order to cross compile 32bit ubuntu on a 64bit ubuntu system `libc6-dev-i386` is required.
Setting `CC="gcc -m32" works.

**Comment by visoeclipse** [comment]
@jeffbmartinez use docker run --rm with sqlite3 , i cannot build , sth is wrong ,  go build -v is nothing with hold..

**Comment by guncha** [comment]
Thanks @jeffbmartinez, it got me on the right track to get cross compilation working for Raspberry Pi 3. In case it's useful for anyone else, here's the Dockerfile I'm using for OSX:

```
FROM dockcross/linux-armv7:latest

# Largely copied from the official Golang image Dockerfile

RUN set -eux; \
  wget -O go.tgz "https://golang.org/dl/go1.9.1.linux-amd64.tar.gz"; \
  tar -C /usr/local -xzf go.tgz; \
  rm go.tgz; \
  export PATH="/usr/local/go/bin:$PATH"; \
	go version

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH
```

And the command to build a package from the package directory:

```shell
PWD=$(pwd)
PROJECT="/go${PWD/"$GOPATH"/}"

docker run --rm -v $GOPATH:/go -w $PROJECT \
  -e "CGO_ENABLED=1" -e "GOARCH=arm" \
  go-arm-linux:latest go build .
```

**Comment by sieunhando** [comment]
After some searching, I found a way to cross compilation on OSX:
1. Install cross-compiler toolchains
```
brew install FiloSottile/musl-cross/musl-cross
brew install mingw-w64
```
2. Build with `-ldflags "-linkmode external -extldflags -static"`

Ex:
```
GOOS=linux GOARCH=amd64 CC="/usr/local/bin/x86_64-linux-musl-gcc" CGO_ENABLED=1 go build -ldflags "-linkmode external -extldflags -static" -o [OUTPUT_BINARY]
```

Reference: https://blog.filippo.io/easy-windows-and-linux-cross-compilers-for-macos/
