### ISSUE TITLE
[Advice needed] Best way to restore a backed up DB while using DB

### ISSUE THREAD

**Issue by maxpert** [mattn/go-sqlite3#1091]
So I've been able to backup my database use the `Backup` mechanism in SQLite. While I can stream this snapshot across I want to figure out what is the best way to restore such database while my app is using the DB. Right now here is what I've done:
 - Open another connection to DB 
 - `ATTACH` the backed up DB as `backup`
 - Start transaction
 - Execute `INSERT OR REPLACE INTO main.<table_name> SELECT * FROM backup.<table_name>;` 
 - Commit transaction

Right now for a large (97MB with almost 600K rows) it takes almost 2 mins to do so. I know there should be a better way out there to transparently old rows (assuming I am not replacing or tampering old rows).

**Comment by rittneje** [comment]
Is your intent to do a normal restore? If so you can back up the backup into the active database in the same way.

**Comment by maxpert** [comment]
So I am working on [this project](https://github.com/maxpert/marmot) where I am trying to replicate changes between multiple SQLite databases. Since I am using raft one of things that might happen is people spin up a node that is totally out of date, and while they are using the DB from a different process marmot has to restore a full database snapshot (I will abstain from going into details on how state machine will ensure that changes while restore was happening will be replayed). To keep matters simple, and discussion on point my limitations are:
 - Other processes might be using the database
 - Sync process gets a backed up database (Snapshot in raft terms)

The only way I can think of right now is what I described above (now I am batch ingesting rows 1000 at a time, to keep DB responsive). Having said that I am looking at various ways people swap out there SQLite databases. What does that look like? Do people take down times during such swaps? Is there a tendency of people just attaching SQLite databases inside database, and atomically switching them or something? Because copying over an existing DB file sounds like bad idea to me.

**Comment by rittneje** [comment]
I don't know all your requirements, but in general I would not expect a new node to be marked as "available" until after the initial restore is complete. Otherwise, any queries against that node will yield very unexpected results (e.g., data inserted long ago is missing).

You should also check out the session extension to see if it could be leveraged for keeping track of the changes that need to be distributed after the initial restore. https://www.sqlite.org/sessionintro.html

Regardless, this question is about SQLite itself, not the Go wrapper, so you should really ask on the forum. https://sqlite.org/forum/forummain

**Comment by maxpert** [comment]
I figured it out. I will share it as document on repo.

**Comment by kateile** [comment]
@maxpert have you shared such info?
