### ISSUE TITLE
Add ability to open database from a "virtual" file

### ISSUE THREAD

**Issue by ribasushi** [mattn/go-sqlite3#1116]
I would like to be able to open an sqlite database given a file descriptor ( no filenames ). The mechanism to do so is described here https://sqlite.org/forum/forumpost/d4ed1b197ec94182 but the URI parser within this library prevents this technique from working.

The reason I want to do this is to utilize crash-safe anonymous inodes as implemented here: https://pkg.go.dev/github.com/tmthrgd/tmpfile#TempFile

The reason I can not use the `:memory:` + `VACUUM INTO`, is because the dataset is very large (almost a TiB ) and working with it in-RAM is problematic.

I am aware that the database will have to be opened with pragmas disabling WAL etc, as they rely on a "filename+extension" mechanism, and that's ok.

Thank you!

**Comment by rittneje** [comment]
I am able to open via a file descriptor exactly as described in the forum post. Please provide a reproducible example, as well as the specific error you are observing.

Also note that depending on if and when you (or the garbage collector) close the original temp file, you may run into issues due to how the database/sql manages connections.
