### ISSUE TITLE
unknown function: pow() in generated field

### ISSUE THREAD

**Issue by rogersm** [mattn/go-sqlite3#1118]
I have a table with a generated field:

```sql
CREATE TABLE PLANET (
        pbg text NOT NULL,

        total_pop INT GENERATED ALWAYS AS (substr(pbg,1,1) * pow(10, population)),
        num_belts INT GENERATED ALWAYS AS (substr(pbg,2,1)),
        num_gasgiants INT GENERATED ALWAYS AS (substr(pbg,3,1))
); 
```

When I query the database with a SELECT, I receive the following golang error:

```
unknown function: pow()

```

but on the other hand, when I query the database directly:

```shell

sqlite> select * from planet;
613|6000000|1|3
603|60000000|0|3
910|9000000|1|0
```
the value is calculated correctly. 

Is this expected behaviour? Do I need to do something to enable pow()?

Platform data:

```shell
# uname -a
Darwin MainServer 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_6

# sqlite3
-- Loading resources from /Users/rogersm/.sqliterc
SQLite version 3.40.0 2022-11-16 12:10:08
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

# cat go.mod
	github.com/jmoiron/sqlx v1.3.5
	github.com/mattn/go-sqlite3 v2.0.3+incompatible

```

**Comment by rittneje** [comment]
You are using a fairly old version of this library. Please upgrade to v1.14.16. (v2 was a mistake and should never be used.) In addition, in order to use math functions such as `pow`, you must build with the `sqlite_math_functions` tag, as mention in the README. Presumably, the reason your sqlite3 CLI works is because it was compiled with the [`-DSQLITE_ENABLE_MATH_FUNCTIONS`](https://www.sqlite.org/compile.html#enable_math_functions) option.

**Comment by rogersm** [comment]
Many thanks for the guidance.
