### ISSUE TITLE
go-sqlite3 is not releasing memory (leading to OOM)

### ISSUE THREAD

**Issue by flosch** [mattn/go-sqlite3#157]
I'm inserting a lot of data into a simple sqlite database and the memory usage keeps increasing until my application gets killed because of OOM.

Related problem here from another user: https://stackoverflow.com/questions/26456253/sqlite-3-not-releasing-memory-in-golang

$ sqlite3 -version

> 3.8.6 2014-08-15 11:46:33 9491ba7d738528f168657adb43a198238abde19e

$ go version

> go version go1.3.3 linux/amd64

I'm on Ubuntu 14.10 amd64.

Please let me know if you need anything.

**Comment by tarikhagustia** [comment]
Hi, @mattn , so every query we need to close prepare and exec?

**Comment by rittneje** [comment]
If you call `Query` then you MUST `defer rows.Close()`.

If you call `QueryRow` then you don't need to close anything as the Go standard library takes care of it for you.

If you call `Prepare` to prepare an ephemeral (e.g., function-scoped) statement, then you MUST `defer stmt.Close()`.

It is never required that you explicitly make prepared statements. This is only a performance improvement you can make for commonly issued queries. If you directly call `Query` or `Exec` then a one-time-use prepared statement will automatically be created and closed.

If you call `Begin` then you MUST ultimately call either `tx.Rollback()` or `tx.Commit()`. Note that both operations are no-ops if the transaction was already committed or rolled back (they return `sql.ErrTxDone`). For this reason I generally `defer tx.Rollback()` as a safety net.

If you call `Exec`, there isn't anything for you to close, but you should only use it for things that modify the database (`INSERT`/`UPDATE`/`DELETE` and most `PRAGMA`s) as issuing a query via `Exec` can have weird results.

Always keep in mind that defers are only executed when the _function_ exits. Be careful about using `defer` inside loops, especially ones that loop indefinitely.

**Comment by joybiswas007** [comment]
I've had a similar problem, but only when using Vim. With an IDE like Zed, RAM usage is around 50MB or less, which is fine. However, when I use Vim, RAM usage increases dramatically. Before my PC froze due to the high RAM consumption, I managed to take a screenshot showing what was causing it. I had this issue for a few weeks and had to do a hard reset every time, but yesterday evening, I managed to take a screenshot. Please check the attached screenshot.

![2025-01-07_15-00](https://github.com/user-attachments/assets/3afa8213-e76f-4582-8e99-5d9fbc331ce3)
