### ISSUE TITLE
Can't go get / go install in official Docker image

### ISSUE THREAD

**Issue by DairyDTP** [mattn/go-sqlite3#224]
Given this Dockerfile

```
FROM golang:1.4.2
RUN go get github.com/mattn/go-sqlite3
```

running

```
go build .
```

will hang for a many minutes at a very high load, then crash:

```
# github.com/mattn/go-sqlite3
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
```

**Comment by DairyDTP** [comment]
Can't reproduce on a fresh Ubuntu VM, with identical docker image.

**Comment by Zebaz** [comment]
I've experienced the same issue on a machine with only 256MB RAM.

I've noticed that while compiling, gcc will take up to 160MB of RAM to compile /go-sqlite3/sqlite3-binding.c (the fact that it's around 200000 lines of code, doesn't help I guess).

After checking dmesg, I noticed Linux killed the cc process due to running out of memory.
 (Out of memory: Kill process 16181 (cc1) ).

For those running into similar problems, I would advise to free up memory by killing processes and use ```go install github.com/mattn/go-sqlite3``` instead of ```go get``` to compile the package once, after which it can be re-used without recompiling the full sqlite3 c bindings.
