### ISSUE TITLE
exec: "FR": executable file not found in %PATH%

### ISSUE THREAD

**Issue by trollito** [mattn/go-sqlite3#495]
Hello,

i am trying to use your package (by the way, thanks you for sharing !) but i have the following error when building:
# github.com/mattn/go-sqlite3
exec: "FR": executable file not found in %PATH%

Do you know what i am missing ?
Regards

**Comment by s-nieuwlandt-dev** [comment]
Hello,

I faced a similar issue with another go library (go-sdl2), and I found a cause for it : 
When I run a `go build -v -work -x -n`, I can see that the library use cgo, which in turn call the C compilation command, by using `FR` instead of `gcc`.
```
FR -I "C:\\Users\\me\\Documents\\Projects\\src\\github.com\\veandco\\go-sdl2\\sdl" -m64 -mthreads ...
```

I'm still analysing why the cgo executable will change the executable's name, but as a workaround, you can create a copy of your `gcc.exe` file in your `MinGW\bin` directory, and rename it `FR.exe` (ugly, but do the job).

I think that this issue is more related to the use of cgo with MinGW.

Hope that will helps.

**Comment by s-nieuwlandt-dev** [comment]
Hi ! 

I've got some news for you :) 

Your issue is not related to `go-sqlite3` but to your Windows/minGW installation. If you check the value of both `%CC%` and `%GCC%` in your console, you will probably see that one of those is set to `FR`. 

`cgo` will use them if they're sets, or use gcc if not (you can see the explanation in this issue : https://github.com/veandco/go-sdl2/issues/317 ).

So you can just unset those environnment vars for fixing this issue.

Hope that will helps.
