### ISSUE TITLE
How do I get the type of the function field in the return result?

### ISSUE THREAD

**Issue by jasonGeng88** [mattn/go-sqlite3#600]
in mysql case:
![image](https://user-images.githubusercontent.com/11816184/41843411-0ef8e1dc-78a0-11e8-9a47-a347925032b4.png)

![image](https://user-images.githubusercontent.com/11816184/41843190-78c1ce40-789f-11e8-80fb-fc4ff754c039.png)

in sqlite3 case:
<img width="579" alt="2018-06-25 5 48 18" src="https://user-images.githubusercontent.com/11816184/41844003-83fc461c-78a1-11e8-89a4-9c2eb599e382.png">

![image](https://user-images.githubusercontent.com/11816184/41843484-359b7160-78a0-11e8-9bd9-34f21944a572.png)

I saw the #395 issue. Is this the same problem?

**Comment by GJRTimmer** [comment]
Actually I'm running into this while trying to write a TestCase for the `ColumnTypeScanType` function.

**Comment by GJRTimmer** [comment]
You need to request the ColumnTypes from within a Range over `rows`. This is due to how SQLite works. See [sqlite.org](https://www.sqlite.org/c3ref/column_blob.html) for more information. SQLite has to have `_step()` called before it can return what you looking for.

If anything is unclear take a peek at the v2.0.0 within result_test.go you can find what you are looking for.
