### ISSUE TITLE
Multiple Foreign Keys Errror

### ISSUE THREAD

**Issue by jainpiyush19** [mattn/go-sqlite3#615]
I am facing an issue with multiple foreign keys where the sqlite3-binding is generating a query of the format 

<pre>
SELECT * FROM TABLE
WHERE (`foreign_key_1`,`foreign_key_2`) IN (("val1,val2"),("val3,val4"))
</pre>

which is not supported by sqlite3 and gives the following error
<pre>
could not prepare statement (1 row value misused)
</pre>

Note : Using GORM as ORM for GoLang

**Comment by G-Codeline** [comment]
i have the same problem when using gorm for golang, is there any solution?

**Comment by rittneje** [comment]
Assuming that is literally the query that gorm is producing, there are three issues with it.
1. In SQLite, string literals are supposed to use single quotes, not double quotes. Depending on how SQLite was configured, [double quotes might be rejected](https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted).
2. Those tuples are misquoted. For example ,it should be `('val1', 'val2')` not `('val1, val2')`.
3. SQLite does not support that kind of `WHERE ... IN` clause. One possible alternative is to use a [common table expression](https://www.sqlite.org/lang_with.html) like so:
```sql
WITH Foo(foreign_key_1, foreign_key_2) AS (
    VALUES ('val1', 'val2'), ('val3', 'val4')
)
SELECT Table.*
FROM Table
INNER JOIN Foo USING (foreign_key_1, foreign_key_2)
```

Since all of these are bugs in gorm, I am going to close this issue. Please file bugs with the gorm maintainers.
