### ISSUE TITLE
Why sqlite3 date type not support?

### ISSUE THREAD

**Issue by Bpazy** [mattn/go-sqlite3#627]
Any schedules please?

**Comment by PaluMacil** [comment]
There is no date type in sqlite3. See https://www.sqlite.org/datatype3.html but if there is a particular behavior you belive is incorrect, please be more specific.

> 2.2. Date and Time Datatype
> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:

- **TEXT** as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
- **REAL** as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
- **INTEGER** as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC.
> Applications can chose to store dates and times in any of these formats and freely convert between formats using the built-in date and time functions.

You can look at #190 to see why you might be having trouble. By default, there is no type affinity for datetime, so you need to cast it to text.

**Comment by Bpazy** [comment]
thanks. I'm sorry about the issue.

**Comment by PaluMacil** [comment]
No problem. It's confusing that sqlite doesn't have a type for it. It makes sense since everyone implements numbers different ways and many applications need to have a local database that has compatible formats with the server's database but... it still makes thinking about it a lot more complex because it's one more thing to remember.
