### ISSUE TITLE
Syntax Validation

### ISSUE THREAD

**Issue by zsrinivas** [mattn/go-sqlite3#706]
it'd be useful if the library provides a validate method to check the syntax of the SQLite query.

one of the use-cases is runtime query input,

**Comment by rittneje** [comment]
Could you clarify what you are looking for? Does [DB.Prepare](https://golang.org/pkg/database/sql/#DB.Prepare) not meet your needs?

**Comment by eightnoteight** [comment]
Hi @rittneje 

So, I'm trying to make sqlbeat like plugin(which is exactly as https://github.com/adibendahan/sqlbeat) as a part of my learning. which will take the sql queries from the config file and on regular intervals will fetch the results for those queries and push them to sink's (sink can any form of output)

and for the same I felt like it's better to do the syntax validation during the config parse, instead of relying on `DB.Prepare` after parsing the config and during the fetching of results

**Comment by rittneje** [comment]
Couldn't you just do it during the config parsing? Something like this:
```go
func validateSyntax(db *sql.DB, query string) bool {
    s, err := db.Prepare(query)
    if err != nil {
        return false
    }
    s.Close()
    return true
}
```

That being said, the SQLite API doesn't really offer a generic syntax validation function. Preparing the query assumes you intend to run it right now, so it also fails if it's syntactically valid but semantically invalid (like trying to select from a non-existent table for example). If this is something you require, I would recommend asking on their mailing list. https://www.sqlite.org/support.html

**Comment by zsrinivas** [comment]
ok, thanks a lot @rittneje
