### ISSUE TITLE
Compile-time options

### ISSUE THREAD

**Issue by gennaios** [mattn/go-sqlite3#708]
Hello,

Having looked over the SQLite recommend build settings and ones that I prefer to use, I have come up with the following: 

export CGO_CFLAGS="-DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_ATOMIC_WRITE -DSQLITE_ENABLE_BATCH_ATOMIC_WRITE -DSQLITE_ENABLE_NULL_TRIM -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_DEFAULT_SYNCHRONOUS=0 -DSQLITE_DEFAULT_AUTOVACUUM=2 -DSQLITE_DEFAULT_PAGE_SIZE=4096"

I'm wondering if these take effect. I get a warning about SQLITE_THREADSAFE being redefined. Others are default and some are included in your settings I believe. Thread safe is mentioned by them as the single setting that most effects performance. As my app is single user, I was trying to use that. Perhaps each setting needs added as a tag for it to work? I am wondering since trying to write a test for pragmas, some don't seem to be set.

The page for reference: 

https://www.sqlite.org/compile.html

**Comment by rittneje** [comment]
Notes for a few of them.

- `SQLITE_THREADSAFE` - If you say 0, that removes _all_ thread-safety from the library. This means that having more than one connection to a database can cause a problem. This includes connections to two _separate_ database, as well as the connection pooling that the Go standard library does unless you tell it not to. For these reasons, turning off thread-safety completely is extremely dangerous and would definitely need to be opt-in. Use at your own risk.
- `SQLITE_OMIT_SHARED_CACHE` - Obviously, this flag would be a problem for anyone that does use shared cache mode. Many issues have been reported by users that connect to in-memory databases and forget to use shared cache mode. This would just compound the issue, especially because if you omit shared cache, it doesn't even complain if you request it in the file URI. It just totally ignores it. As such, this would definitely need to be opt-in.
- `SQLITE_DEFAULT_FOREIGN_KEYS` Having foreign keys on by default makes sense, as that is what most users probably expect. However, this would be a breaking change for some legacy applications, so there would likely need to be an opt-out.

In any case, if you want to custom compile SQLite for your personal needs, I would recommend building the library from source and then just dynamic linking by passing the `libsqlite3` build flag to Go. See https://github.com/mattn/go-sqlite3/blob/master/sqlite3_libsqlite3.go

**Comment by gennaios** [comment]
I had tried building it and linking to libsqlite3 from homebrew shortly after your message, and had some error I wasn't able to figure out at the time. I will try again later.

My interest in these parameters is from following SQLite's recommended build settings. They are as such for it seems maximum performance in a single-threaded application, which is the case for my use. It's possible some such as `SQLITE_THREADSAFE` are not appropriate for `database/sql` drivers; of that I am unsure.

Perhaps later some of these can be added as tags. I had tried experimenting with the `crawshaw/sqlite` driver and performance was only slightly better; not enough to make a big difference. As such, the options are less important to me now. But I may revisit them sometime later.
