### ISSUE TITLE
Missing leading “file:” in DSN casuse "database is locked" when querying concurrently

### ISSUE THREAD

**Issue by CxdInitial** [mattn/go-sqlite3#833]
Once I forgot to add leading `file:` to DSN. And then concurrent queries would get `database is locked`.

Here is code:
```
const n = 100
const c = 4

func main() {
	conn, err := sql.Open("sqlite3", "tmp.db?_locking=EXCLUSIVE&cache=shared")
	if err != nil {
		panic(err)
	}
	tx, err := conn.BeginTx(context.Background(), nil)
	if err != nil {
		panic(err)
	}
	_, err = tx.Exec("create table test(a int unique)")
	if err != nil {
		panic(err.Error())
	}
	for i := 0; i < n; i++ {
		_, err = tx.Exec("insert into test values(?)", i)
		if err != nil {
			panic(err)
		}
	}
	err = tx.Commit()
	if err != nil {
		panic(err)
	}

	wg := sync.WaitGroup{}
	wg.Add(c)
	per := n / c
	for i := 0; i < c; i++ {
		beg := per * i
		go func() {
			for i := 0; i < per; i++ {
				row := conn.QueryRow("select 1 from test where a=?", beg+i)
				var got int
				err := row.Scan(&got)
				if err != nil {
					fmt.Printf("i:%d err:%s\n", beg+i, err.Error())
				}
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
```

Here is output:
```
i:25 err:database is locked
i:50 err:database is locked
i:0 err:database is locked
```

Database file is normal, here is output of `ls`:
```
main.go  tmp.db  tmp.db-journal
```

After I add `file:`, no error occurs. So I guess it's because of the absence of `file:`, maybe I am wrong.

**Comment by rittneje** [comment]
As per your DSN, you are using SQLite's exclusive locking mode feature. This means that as soon as the database connection in question writes to the database (such as your "create table" command), that specific connection retains an exclusive lock on the database. Consequently, no other database connection can access the database, not even just for reading, until that connection is closed. https://www.sqlite.org/pragma.html#pragma_locking_mode

Meanwhile, despite its name, the `*sql.Conn` object returned by `sql.Open` does not actually represent a single connection, but rather a pool of connections. Since you are trying to issue multiple queries in parallel, this connection pool sometimes elects to open new database connections. But since the original connection still holds its exclusive lock, these new connections will be unable to acquire the shared lock they need to read the database, and thus ultimately fail with a "database is locked" error. If however the connection pool happens to use the original connection holding the exclusive lock, the query will work fine.

Thus my guess is that it is merely coincidence that adding the missing "file:" prefix works. However, I am curious why are using exclusive locking mode, especially if you intend to be doing queries in parallel. Can you elaborate on your use case?

**Comment by CxdInitial** [comment]
> Meanwhile, despite its name, the *sql.Conn object returned by sql.Open does not actually represent a single connection, but rather a pool of connections.

If I manually set max open connections to **one** using `SetMaxOpenConns`, no error occurs. I should do this.
```
conn.SetMaxOpenConns(1)
```

> Thus my guess is that it is merely coincidence that adding the missing "file:" prefix works.

I also want to accept that. But the result isn't quite convincing. On my computer, 100% fail without `file:`, but 100% succeed with `file:`.

> I am curious why are using exclusive locking mode, especially if you intend to be doing queries in parallel. Can you elaborate on your use case?

For the first reason listed in doc.

> There are three reasons to set the locking-mode to EXCLUSIVE.
>
>    The application wants to prevent other processes from accessing the database file.
>    The number of system calls for filesystem operations is reduced, possibly resulting in a small performance increase.
>    WAL databases can be accessed in EXCLUSIVE mode without the use of shared memory. (Additional information)

**Comment by rittneje** [comment]
I did some further investigation and have found the source of the issue.

This library will use any query string parameters after the "?" regardless of whether your filename starts with "file:". https://github.com/mattn/go-sqlite3/blob/4c2df3cc4614a8001c1afdebcbda0fcf6e045719/sqlite3.go#L1045-L1047

However, if your filename does not start with "file:", this library will strip off the query string suffix before passing it to SQLite. https://github.com/mattn/go-sqlite3/blob/4c2df3cc4614a8001c1afdebcbda0fcf6e045719/sqlite3.go#L1367-L1369

Consequently, omitting the "file:" prefix results in your database connecting using exclusive locking mode, but not shared cache mode. That results in sporadic "database is locked" errors due to connection pooling races, as described earlier.

By including the "file:" prefix, you are now using both exclusive locking mode and shared cache mode. The interaction of these two features does not appear to be explicitly documented, but evidently the shared cache allows other connections from the same binary to share the not-so-exclusive lock. Whether this is a bug or a feature in SQLite is unclear.

Note that even if this library did not chop off the query string suffix, you would have still had a similar issue, because SQLite itself refuses to honor any query string parameters unless the filename starts with "file:". https://www.sqlite.org/uri.html
> Since SQLite always interprets any filename that does not begin with "file:" as an ordinary filename regardless of the URI setting, and because it is very unusual to have an actual file begin with "file:", it is safe for most applications to enable URI processing even if URI filenames are not currently being used. 

Perhaps this library should instead add the missing "file:" prefix if it is absent to avoid issues like the one you encountered here. However, that could lead to the same backwards compatibility issues that made the SQLite authors require the prefix to be explicit in the first place.

**Comment by CxdInitial** [comment]
In conclusion, **every one who wants to add parameters in dsn should add "file:" prefix.**
Thanks for your effort.
