### ISSUE TITLE
How to statically link an extension?

### ISSUE THREAD

**Issue by dstotijn** [mattn/go-sqlite3#866]
Has anybody had success statically link sqlite3 extensions, e.g. using `sqlite3_auto_extension`? I've tried the approach from [this issue](https://github.com/mattn/go-sqlite3/issues/141), but without any luck; get the following panic:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x600 pc=0x4523933]

runtime stack:
runtime.throw(0x476de74, 0x2a)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/signal_unix.go:704 +0x48c

goroutine 8 [syscall]:
runtime.cgocall(0x4523370, 0xc000ac3048, 0xc000aa5450)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc000ac3018 sp=0xc000ac2fe0 pc=0x400601b
github.com/dstotijn/hetty/pkg/db/sqlite._Cfunc_auto_extension(0x0)
        _cgo_gotypes.go:46 +0x49 fp=0xc000ac3048 sp=0xc000ac3018 pc=0x448e4e9
(...)
```

Without this, the fallback I guess means including a lib (e.g. a `.so` or `.dylib` file) when building and bundling (arch specific) releases. But this makes it more tricky for users, because the binary would need (flag) configuration to point to the entrypoint of the lib. Ideally there's just one binary (compiled for a specific arch) that contains everything.

**Comment by rittneje** [comment]
The process for statically linking an extension is described here. https://sqlite.org/loadext.html#statically_linking_a_run_time_loadable_extension

I _think_ once #785 is merged, it would be possible to directly call your `sqlite3_extension_init` function as described.

**Comment by riyaz-ali** [comment]
You can wrap it in a `go` package and use [`sqlite_auto_extension`](https://www.sqlite.org/c3ref/auto_extension.html). 

For example, with the default `csv` extension, you can grab the [`csv.c` source file](https://raw.githubusercontent.com/sqlite/sqlite/master/ext/misc/csv.c) and add it to a `go` package (say) `csv`.  Then, create a `csv.go` file with following content:

```golang
package csv

// #cgo LDFLAGS: -lsqlite3
// #include <sqlite3.h>
//
// // extension function defined in csv.c
// extern int sqlite3_csv_init(sqlite3*, char**, const sqlite3_api_routines*);
//
// // Use constructor to register extension function with sqlite.
// void __attribute__((constructor)) init(void) {
//   sqlite3_auto_extension((void*) sqlite3_csv_init);
// }
import "C"
```

After this, you can import it in your `main` package as,

```golang
import (
    _ "example.io/app/csv" // assuming module name is example.io/app and package is in csv directory
)

// somewhere else in your code
_, err := db.Exec("CREATE VIRTUAL TABLE xyz USING csv('/path/to/data.csv')")
```

To build this, you'd need to use something like

```shell
go build -tags libsqlite3 example.io/app
```

This would cause it to _link_ against the system's `sqlite3` package and would cause the extension to register with all the database connection.

--------------------------------------------------------

If you don't want to link against your system's `sqlite3` package (maybe it's too old?), then you can drop the `LDFLAGS` pragma above and build without `-tags libsqlite3`. 

To build this way, you'd have to instruct your linker to _ignore un-resolved symbol_ errors in intermediate `.o` files. You can do this via `CGO_LDFLAGS` environment variable (as the flag required [are not whitelisted](https://fipress.org/knowledge/invalid-flags-in-cgo-ldflags-pkg-config-or-invalid-flag-in-pkg-config) due to security reasons)

```shell
CGO_LDFLAGS="-undefined dynamic_lookup" go build example.io/app # for darwin+clang
# or 
CGO_LDFLAGS="-Wl,--unresolved-symbols=ignore-in-object-files" go build example.io/app # for linux+gcc
```

Reason to suppress this error is because the `sqlite3` symbols (generated from [`sqlite3-binding.c`](https://github.com/mattn/go-sqlite3/blob/master/sqlite3-binding.c)) are only available when the final application is being linked and not during intermediate package compilation.

You can also link against your own `libsqlite3.a` by following steps [outlined here](https://github.com/mattn/go-sqlite3/issues/858#issuecomment-701531930)

-------------------------------------------------------------

P.S. I've also recently written a go package that allows one to write `sqlite3` extensions in `golang`. It's designed to play well with `github.com/mattn/go-sqlite3` driver. You can check it out at [`github.com/riyaz-ali/sqlite`](https://github.com/riyaz-ali/sqlite) 🙂

**Comment by dstotijn** [comment]
> If you don't want to link against your system's `sqlite3` package (maybe it's too old?), then you can drop the `LDFLAGS` pragma above and build without `-tags libsqlite3`.
> 
> To build this way, you'd have to instruct your linker to _ignore un-resolved symbol_ errors in intermediate `.o` files. You can do this via `CGO_LDFLAGS` environment variable (as the flag required [are not whitelisted](https://fipress.org/knowledge/invalid-flags-in-cgo-ldflags-pkg-config-or-invalid-flag-in-pkg-config) due to security reasons)
> 
> ```shell
> CGO_LDFLAGS="-undefined dynamic_lookup" go build example.io/app # for darwin+clang
> # or 
> CGO_LDFLAGS="-Wl,--unresolved-symbols=ignore-in-object-files" go build example.io/app # for linux+gcc
> ```
> 
> Reason to suppress this error is because the `sqlite3` symbols (generated from [`sqlite3-binding.c`](https://github.com/mattn/go-sqlite3/blob/master/sqlite3-binding.c)) are only available when the final application is being linked and not during intermediate package compilation.

@riyaz-ali and @rittneje Thank you so much for your replies!

When using the approach of _not_ linking against the system's `sqlite3` lib from @riyaz-ali's comment, (e.g. omitting the `LDFLAGS` pragma in the .go file, not using `-tags` and using a `CGO_LDFLAGS` env var to instruct the linker to ignore unresolved symbols), I still get this error:

```
# github.com/dstotijn/hetty/pkg/db/sqlite/regexp
pkg/db/sqlite/regexp/regexp.go:3:11: fatal error: sqlite3.h: No such file or directory
 // #include <sqlite3.h>
           ^~~~~~~~~~~
compilation terminated.
```

How do I get the linker to link using the (amalgamated) sqlite3 lib from `github.com/mattn/go-sqlite3`?

With the aforementioned setup I can only get the linking to succeed when I first install `sqlite3` system wide (e.g. via Homebrew on Mac, or via `apt-get` on Debian). I've tried changing `#include <sqlite3.h>` to `#include <sqlite3-binding.h>` in my .go file and adding `-L/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.4` to `CGO_LD_FLAGS`, but this doesn't work either.

I'm cross compiling using [troian/golang-cross](https://github.com/troian/golang-cross).

Do you have any ideas what I'm doing wrong?

**Comment by rittneje** [comment]
`-L` specifies directories for libraries. You want `-I`, which specifies directories for header files.

**Comment by dstotijn** [comment]
> `-L` specifies directories for libraries. You want `-I`, which specifies directories for header files. Alternatively, set the `CPATH` environment variable.

@rittneje Thanks (again)! I did try `-I` before, but (erroneously) used it in `CGO_LDFLAGS`. Using it in `CGO_CFLAGS` or `CPATH` works! 🎉 

The only remaining issue is when cross compiling for windows amd64; the toolchain I'm using (MinGW) doesn't seem to support `--unresolved-symbols` ([ref](https://sourceforge.net/p/mingw-w64/mailman/message/35089852/)) and linking results in:

```
# github.com/dstotijn/hetty/pkg/db/sqlite/regexp
/usr/bin/x86_64-w64-mingw32-ld: $WORK/b165/_x002.o:regexp.cgo2.c:(.text+0x66): undefined reference to `sqlite3_auto_extension'
collect2: error: ld returned 1 exit status
```

But that's outside the scope of this issue I reckon. I might opt to use system installed libsqlite3 just for Windows to avoid this scenario.
