### ISSUE TITLE
Support VFS when opening a db

### ISSUE THREAD

**Issue by guenhter** [mattn/go-sqlite3#876]
Hi,

is there a reason why it is currently not supported to define a VFS via the connection string when opening a DB?

I guess everything is prepared for it but the `zVfs` parameter is just not use and always set to `nil`
https://github.com/mattn/go-sqlite3/blob/92f580b350d88e068bfbe223ea51f64044c0f280/sqlite3.go#L1377

Would you mind to add the vfs to the connection uri parameters, so that e.g. this can be done:

```
db, err := sql.Open("sqlite3", "test.db?cache=shared&mode=rwc&vfs=unix-dotfile")
```

(I guess as a start, it is good enough only supporting the build-in-VFS'; registering new VFS' can be added if needed later)

**Comment by mattn** [comment]
Could you please try https://github.com/mattn/go-sqlite3/pull/877 ?

**Comment by jtarchie** [comment]
This may not work as expected. I'm trying to load an extension, a VFS, but it keeps giving me the `no such vfs:`. I believe it is because the [`sqlite3_open_v2`](https://github.com/mattn/go-sqlite3/pull/877/files#diff-2b10fcf999dec2c93bce3364fdeefd688eda6ad78934ac1a2d8b359b57ee7687R1385) happens before the driver has loaded the extension.
