### ISSUE TITLE
Problem with having concurrent access to csv virtual tables

### ISSUE THREAD

**Issue by deka108** [mattn/go-sqlite3#887]
Hi,

I wanted to load temporary csv files into virtual tables in sqlite3 and use them for my rpc services. We wanted to load virtual tables once at the beginning of a session and have the virtual tables accessed by multiple goroutines / rpc services concurrently during the session. The subsequent accesses will only be either read-only accesses or insert/deletion operations on the virtual tables. We will run this on multiple servers, so each server will create a single db connection, possibly to a single or multiple dbs.  Note that we are not modifying the actual files under the virtual tables, so after we finished using the virtual tables we can drop them.

I discovered that there is a problem with subsequent concurrent accesses to virtual tables under multiple goroutines. For example, although we had loaded the virtual tables, during the concurrent access only a single goroutine out of multiple goroutines recognizes the virtual tables that we have created exist and return the correct results.

This concurrency issue does not occur if we only query tables that are already existing in sqlite db. However, we are interested in virtual tables as we plan to have the virtual tables to exist only during the session and delete them after the session. 

I have tried several dataSource options, including using the four options in the source code below `:memory:`, `file::memory:?cache=shared`, `file:db_%d?cache=shared&mode=memory`, `db_%d.db` but they all have the same concurrency issues with virtual tables. 

### Sample Source Code Excerpt

```go
type struct server{
	db       *sql.DB
}

// a single operation session
func (s *server) RunOp(ctx context.Context, in *OpRequest) (*OpResponse, error) {
	s.initTable(in.GetTable1Name(), in.GetTable1Path())
	s.initTable(in.GetTable2Name(), in.GetTable2Path())
	s.testRunQuery(in.GetTable1Name(), in.GetTable2Name())

	// delete tables before we return a response, we will no longer use the virtual tables so we can safely remove them from db

	return &OpResponse{}, nil
}

func (s *server) initTable(tableName, fullTablePath){
	queryStmt := fmt.Sprintf("CREATE VIRTUAL TABLE temp.`%s` USING csv(filename='%s', header=true);",
		tableName, fullTablePath)
	_, err := s.db.Exec(queryStmt)
	if err != nil {
		log.Fatal().Err(err)
	}
}

func (s *server) testRunQuery(table1 string, table2 string) {
	var wg sync.WaitGroup
	for i := 0; i < 3; i++ {
		wg.Add(1)
		// try some queries
		go func(i int) {
			defer wg.Done()
			s.runQuery(fmt.Sprintf("SELECT * FROM %s;", table1))
		}(i)
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			s.runQuery(fmt.Sprintf("SELECT * FROM %s;", table2))
		}(i)
	}
	wg.Wait()
}

func (s *server) runQuery(query string){
	rows, err := s.db.Query(query)
	if err != nil {
		log.Fatal().Err(err)
	}
	if rows != nil {
		defer rows.Close()
		
		// get the schema
		cols, err := rows.ColumnTypes()
		if err != nil {
			log.Fatal().Err(err)
		}
		for idx := range cols {
			fmt.Println(fmt.Sprintf("colName: %s, colType: %s", cols[idx].Name(), cols[idx].DatabaseTypeName()))
		}
	} else {
		fmt.Println("No table available")
	}
}

func Serve(int port){
	// setup connection
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		log.Fatal().Err(err).Msg("failed to listen")
	}
	log.Info().Msgf("server listening at %v", lis.Addr())

	// Set up a db connection
	csvLibPath := os.Getenv("CSV_EXT_PATH")
	if csvLibPath == "" {
	log.Fatal().Msg("No path to csv extension")
	}
	
	sql.Register("sqlite3_with_extensions", &sqlite3.SQLiteDriver{Extensions: []string{csvLibPath}})
	
	// run an SQLite DB on a single worker for serving data

        // option 1: using memory
	// dbPath := ":memory:"
       
        // option 2: using shared memory
	dbPath = "file::memory:?cache=shared"

	// option 3: using named memory
	// dbPath = fmt.Sprintf("file:db_%d?cache=shared&mode=memory", port)
	
        // option 4: using db
	// dbPath := fmt.Sprintf("data-%d.db", port)
	// os.Remove(dbPath)
        // defer os.Remove(dbPath)
	
	db, err = sql.Open("sqlite3_with_extensions", dbPath)
        s := server{
                db: db
        }
        if err := s.Serve(lis); err != nil {
		log.Fatal().Err(err).Msg("failed to serve")
	}
}
```

- `csvLibPath` is the absolute path to the csv extension binary built from https://www.sqlite.org/src/artifact?ci=trunk&filename=ext/misc/csv.c 
-  Across multiple servers, I recognize that the `runQuery` on virtual table called in `testRunQuery` is only successful on a single goroutine per server where rows will not be nil and we will able to read some data out of it. So the rest of the goroutines will have nil `rows`. This concurrency issue does not occur if we query an existing table in some sqlite db as we will be successful in all the `runQuery` goroutines.

### Questions
So my questions are:
1. How do we properly set up the data source for db such that we can have multiple servers running different db, but within a single server, goroutines and services on that server are able to access the virtual tables concurrently?
2. What's the best way to load files on demand to sqlite and delete it after we finished using it in go? currently, we were thinking of virtual tables but open to other solutions

Thank you so much

**Comment by rittneje** [comment]
Can you explain your use case in further detail? If all your server needs to do is read data from a CSV file, why use SQLite at all? You can just parse the file directly with the [csv package](https://golang.org/pkg/encoding/csv/).

With regards to the issue you are directly observing, it is happening because:
1. Go's `*sql.DB` object is actually a connection _pool_. It does not allow multiple goroutines to access the same underlying connection simultaneously. So each goroutine is actually working against a separate connection, created automatically by the pool.
2. In SQLite, temporary tables are scoped to the connection that created them.

There are two ways around this:
1. Do all of your database operations within a call to `RunOp` in a single [transaction](https://golang.org/pkg/database/sql/#DB.Begin). That will force all the operations within the transaction to run on the same connection.
2. Do all of your database operations within a call to `RunOp` on a single [connection](https://golang.org/pkg/database/sql/#DB.Conn).

Note that you will need to defer dropping the virtual tables in `RunOp`, to prevent issues on subsequent requests that are using the same table name.

**Comment by deka108** [comment]
Oooh that makes sense! Thank you.

You're right, we can always parse the files directly instead of using sqlite. We found sqlite to be helpful because of the schema detection and support for simple and advanced sql queries inside `RunOp` which we require for our real services. I guess what I'm looking for is actually something similar to dataframe in go. However, databases usually allow loading data by pages on-demand depending on the query so it is still worth exploring. Thanks!

**Comment by deka108** [comment]
hi @rittneje, 

I have a follow-up question. We have a new use case where instead of only reading, we also want to modify the table by doing insertions and deletions on the virtual tables. If we want to make the virtual tables as well as the changes to the virtual tables available across multiple goroutines, does this mean the only option we have is to run the queries on a single connection? 

Similar to the previous use cases, after we finished using the virtual tables on a session, we will drop the virtual tables

Thank you

**Comment by rittneje** [comment]
What exactly is a session in this context? When does it start/end? How would multiple goroutines come to operate against the same session simultaneously?

**Comment by deka108** [comment]
A session is the duration of a single rpc call. Within the single rpc call, we will initialize virtual tables based on the files requested in the rpc call and perform concurrent distributed sql queries on the initialized virtual tables. After all the required sql operations are finished, then the rpc call is finished and we can safely delete the virtual tables as we no longer need them.

**Comment by rittneje** [comment]
Attempting to perform both reads and writes in parallel for a given session would seem like a poor API contract. For example, suppose my RPC call has the following two operations:
1. `INSERT INTO Foo VALUES (...)`
2. `SELECT * FROM Foo`

If you attempt to do both of those in parallel, then it is effectively random chance whether the select will return the record from the insert.

That being said, I believe it is safe to use a single transaction concurrently for reads and writes, both at the Go level and the SQLite level. However, because of the locking involved, you may not actually notice any performance benefit at all. To that end, my recommendation would be to prefer a stable API contract over parallelizing. That is, guarantee that all the operations within a single RPC call will be executed serially, and if the client wants them to be parallel instead, they may execute their RPC calls in parallel.

With such a contract, you _could_ then implement your server such that a sequence of read operations are performed in parallel, while write operations are performed serially (with respect to each other and to read operations). For example:
1. read A
2. read B
3. write C
4. write D
5. read E

You could perform 1 and 2 in parallel, then 3, then 4, and finally 5.

Another option is to establish multiple connections to a _named_ in-memory database using shared cache mode, and create the csv tables in the main schema rather than the temp schema. Then you could truly have multiple concurrent readers, each reading through a separate connection. However attempting to perform writes concurrently with other operations is still ill-defined as mentioned above, and may lead to sporadic "database table is locked" errors unless you build with the `sqlite_unlock_notify` tag.

```go
func (s *server) HandleRequest(ctx context.Context) error {
    db, err := sql.Open("sqlite3", "file:<guid>?mode=memory&cache=cached")
    if err != nil {
        return nil, err
    }
    defer db.Close()

    // Make sure there is always at least one open connection until the entire RPC completes.
    // The database is deleted when the last connection to it is closed.
    // See https://sqlite.org/inmemorydb.html
    db.SetConnMaxLifetime(0)
    db.SetMaxIdleConns(...)    // > 0
    db.SetMaxOpenConns(...)

    if err := db.Ping(); err != nil {
        return nil, err
    }

    // create virtual tables in main schema

    // do operations in parallel against db
}
```

**Comment by deka108** [comment]
Ah, I see. Noted and thanks so much for the help! I'm a bit new to using in-memory db in go so the discussions had been very helpful. Also, we do have barrier implementations in-place to separate the read and write phases so the concurrent operations are isolated to each phase. Thanks!
