### ISSUE TITLE
Panic: driver.Stmt is nil, not *sqlite3.SQLiteStmt in exec()

### ISSUE THREAD

**Issue by otoolep** [mattn/go-sqlite3#959]
Attempting to debug https://github.com/rqlite/rqlite/issues/830

Can anyone tell me why this might be happening? I've looked at the go-sqlite3 code, and can't see how this could happen. How could:

https://github.com/mattn/go-sqlite3/blob/3392062c729d77820afc1f5cae3427f0de39e954/sqlite3.go#L1744

return anything but a `*sqlite3.SQLiteStmt` and a `nil` error? I'm wondering if I have a race in rqlite that is setting something to `nil`. But a basic reading of the panic implies that `(c *SQLiteConn) prepare()` is truly returning `nil, nil`. Is that possible?

Background:

rqlite is hitting the following issue:
```
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt

goroutine 25 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc00018ea20, 0xddbb00, 0xc00002e0a0, 0xc00024bc00, 0x6a8, 0x1414c70, 0x0, 0x0, 0xc000379920, 0x47b8bb, ...)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x72e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc00018ea20, 0xc00024bc00, 0x6a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x145
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc000379ab0, 0xcfd300, 0xc0001914d0, 0xc000226000, 0x201, 0x0, 0x0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/db/db.go:321 +0x2aa
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0001914d0, 0xc000226000, 0xc000ef6101, 0x0, 0x0, 0x0, 0x0, 0xc0001f83f0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000182780, 0xc000460060, 0x0, 0x0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/store/store.go:950 +0x3c6
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0019a8040)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2bd
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00028a200, 0x1, 0x40)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc0002b6000)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0002b6000, 0xc000194cd0)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66
```

**Comment by otoolep** [comment]
This is the line in my fork which is panicking: https://github.com/rqlite/go-sqlite3/blob/master/sqlite3.go#L803

My fork is not much different than upstream.

**Comment by rittneje** [comment]
It looks like you are directly interacting with `*sqlite3.Conn`, etc. rather than going through the standard database/sql package. As such, it is _possible_ that first `sqlite3_prepare_v2` fails, but then by the time it is fetching the error code, some other goroutine has performed another operation, resetting the error code to `SQLITE_OK` and confusing everything.

https://github.com/rqlite/go-sqlite3/blob/91ac2e4a34548c70766960ea3747c465050784fd/sqlite3.go#L1798-L1801
https://github.com/rqlite/go-sqlite3/blob/91ac2e4a34548c70766960ea3747c465050784fd/sqlite3.go#L759-L763

See https://www.sqlite.org/c3ref/errcode.html
> When the serialized threading mode is in use, it might be the case that a second error occurs on a separate thread in between the time of the first error and the call to these interfaces. When that happens, the second error will be reported since these interfaces always report the most recent result. To avoid this, each thread can obtain exclusive use of the database connection D by invoking sqlite3_mutex_enter(sqlite3_db_mutex(D)) before beginning to use D and invoking sqlite3_mutex_leave(sqlite3_db_mutex(D)) after all calls to the interfaces listed here are completed.

If this is indeed the case, then you need to add proper thread-safety around your database access.

**Comment by otoolep** [comment]
@rittneje -- thanks for that. Yes, I've used direct access to the SQL code for many years, without trouble, but I see your point.

One of my suspicions is exactly as you say -- that a higher-up layer in rqlite is changing the `*sqlite3.Conn` object when it shouldn't i.e. that there is a race in my code that I have not properly synchronized. I was aware of this requirement, and had thought I had coded it correctly, but it seems like I *might* have missed a case. I'll continue digging into the code.

I'll close this issue, as you've given me a lead. Any other ideas are welcome of course.

**Comment by otoolep** [comment]
@rittneje -- maybe you can help me improve my use of go-sqlite3 code.

Your statement implies ("some other goroutine has performed another operation") that even two concurrent queries (SELECTs) on the same connection could cause this issue. Doesn't that imply I can't perform two reads of the database on the same connection? Does using the database/sql help with this, avoid the issue, but still give me concurrent read performance?

I guess one way to deal with this is to use a connection pool?

**Comment by otoolep** [comment]
I know I can't perform two writes, but I thought two reads would be OK. Clearly not, or I update my fork to not check lastError(). But that would mean losing valuable error information.

**Comment by rittneje** [comment]
> Doesn't that imply I can't perform two reads of the database on the same connection?

Unfortunately, I think that may be the case. This seems to be a fundamental issue with the way SQLite reports errors.

> Does using the database/sql layer help with this, avoid the issue, but still give me concurrent read performance? How does it cope with this issue? Will I see synchronization code in that layer somewhere?

Yes, database/sql internally has locking mechanisms to prevent concurrent use of the same driver connection. See https://pkg.go.dev/database/sql/driver#Conn
> Conn is a connection to a database. It is not used concurrently by multiple goroutines. 

Note that it is fine for two (or more) separate database connections to read concurrently. And with WAL mode, it is even fine to read the database concurrently with a write.

Also note that if you intend to use shared cache mode with multiple connections, it has [some pitfalls](https://www.sqlite.org/unlock_notify.html).

**Comment by rittneje** [comment]
@otoolep There is another possible explanation for the issue you are seeing.

> If an interface fails with SQLITE_MISUSE, that means the interface was invoked incorrectly by the application. In that case, the error code and message may or may not be set. 

If `sqlite3_prepare_v2` returns `SQLITE_MISUSE`, you could see this occur, regardless of any thread-safety problems in play. However, I don't know what specifically could cause it to return that. One thing you can try is to set a logger, since it seems like SQLite will output a log message whenever `SQLITE_MISUSE` occurs. https://www.sqlite.org/errlog.html

**Comment by otoolep** [comment]
Thanks for the heads-up @rittneje 

What I have done is committed a change that does very simple -- but robust -- synchronization of the SQLite connection. Check out https://github.com/rqlite/rqlite/pull/834

The group that hit this issue should know fairly soon if this patch addresses the issue, which will tell us if rqlite had connection management issues all along (related to its use of Goroutines). If the patch addresses the issue, I'll implement in a more sophisticated manner, perhaps with proper connection pooling. If not, we'll have to continue the investigation.

**Comment by otoolep** [comment]
@rittneje -- I should probably just modify rqlite such that it uses the `database/sql` interface instead of accessing `*sqlite3.Conn` directly. That way I just get all the advantages of multi-thread support *and* connection pooling, without writing the code myself.

Does this sound reasonable to you?

**Comment by otoolep** [comment]
Did mean to comment, but didn't mean to open.

**Comment by rittneje** [comment]
@otoolep I think that is reasonable, provided that it doesn't cause an unacceptable performance degradation for you.

Some helpful recommendations:
1. Turn on WAL mode with `_journal=WAL`. This allows reads to happen concurrently with writes.
2. Do NOT turn on shared cache mode. The SQLite authors actively discourage its use. I would only consider this as an absolute last resort if you are facing performance issues. If you do choose to turn this on, you will want to build with the [`sqlite_unlock_notify`](https://github.com/mattn/go-sqlite3/blob/master/sqlite3_opt_unlock_notify.go) tag or else you can get random `SQLITE_LOCKED` errors (not to be confused with `SQLITE_BUSY`, even though the error messages are similar).
3. Configure the connection pool via [`SetConnMaxIdleTime`](https://pkg.go.dev/database/sql#DB.SetConnMaxIdleTime), [`SetConnMaxLifetime`](https://pkg.go.dev/database/sql#DB.SetConnMaxLifetime), [`SetMaxIdleConns`](https://pkg.go.dev/database/sql#DB.SetMaxIdleConns), and [`SetMaxOpenConns`](https://pkg.go.dev/database/sql#DB.SetMaxOpenConns).
4. When starting a transaction that will be (or could be) writing to the database, use `BEGIN IMMEDIATE`. Otherwise if two connections try to write to the database you can get `SQLITE_BUSY` errors. A simple way to achieve this is to make two pools - one opened with `mode=ro` and the other opened with `mode=rw&_txlock=immediate`. The latter can be throttled to a pool of size 1 since SQLite doesn't support multiple concurrent writes anyway.
5. If you need to access some specific functionality of `*sqlite.Conn`, such as [`Backup`](https://pkg.go.dev/github.com/mattn/go-sqlite3#SQLiteConn.Backup), you can leverage the relatively new [`Raw`](https://pkg.go.dev/database/sql#Conn.Raw) method of `*sql.Conn`.

**Comment by otoolep** [comment]
@rittneje -- thanks, very helpful. I'm trying out moving rqlite to the sql/database layer.

One thing I've never figured out however. How does one cope with `SELECT *` with [Scan](https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L2100). When using the driver directly I could just pass `[]driver.Value` to rows.Next(), and the driver did the work. But this doesn't work when using the sql/database:
```
			dest := make([]interface{}, len(rows.Columns))
			if err := rs.Scan(dest...); err != nil {
				return nil, err
			}
```

What am I missing here? Do I need to somehow reproduce all the code in the driver that looks at the number of columns? It's not clear how I create the right variable to pass to Scan(). This is important because rqlite doesn't know the queries ahead time, and has to be able to handle `SELECT *`.

**Comment by otoolep** [comment]
I mean https://pkg.go.dev/database/sql#Rows.Scan -- it's not clear to me how to build up the right variable to pass to that function, to collect the column values.

**Comment by rittneje** [comment]
`Rows.Scan` needs pointers so it can put the output values somewhere (similar to `json.Unmarshal`). So you can't just pass a bunch of `nil` `interface{}` values. Instead you need pointers. Something like this should work.

```go
dest := make([]interface{}, len(rs.Columns()))
ptrs := make([]interface{}, len(dest))
for i := range ptrs {
    ptrs[i] = &dest[i]
}
if err := rs.Scan(ptrs...); err != nil {
    return nil, err
}

// now use dest
```

Note that the reason for the distinction here is that `sql.Rows.Scan` is variadic, whereas `driver.Rows.Next` just takes a normal slice.

**Comment by otoolep** [comment]
Nice, thank you @rittneje

**Comment by otoolep** [comment]
I have successfully moved rqlite to the Go sql/database abstraction. See https://github.com/rqlite/rqlite/pull/835

Thanks again @rittneje for your help and advice.

**Comment by otoolep** [comment]
@rittneje -- do you know if connection pooling operates with in-memory databases, opened using `mode=memory`?

E.g.:

`db, err := sql.Open("sqlite3", "file:memdb1?mode=memory")`

and then calling 

`Conn()` 

on the `db` object. Will I get a connection to the same in-memory database? The SQLite docs are a little unclear about this, I'll do some testing tomorrow -- but some of the results I'm seeing imply I'm not getting a connection to the same in-memory database.

**Comment by rittneje** [comment]
For "classic"  in-memory databases, you must turn on shared cache mode in order for two separate connections to operate against the same in-memory database. Note that this has the aforementioned drawbacks around the need for `sqlite_unlock_notify`.

Furthermore, note that if the last connection to that database closes (which could happen in the background due to the connection max idle time, for example), then that in-memory database is irreversibly lost.

See https://sqlite.org/inmemorydb.html#sharedmemdb for details.

There is also the preferred alternative of using a memdb VFS instead for this, as discussed in this forum thread: https://sqlite.org/forum/forumpost/c1004073ca76117f However, I personally have never used it.

**Comment by otoolep** [comment]
Hmmm, thanks, that's what I was afraid off. I'll need to think about this.

**Comment by rittneje** [comment]
Can you elaborate on rqlite's use cases for in-memory databases?

**Comment by otoolep** [comment]
rqlite uses an in-memory database by default -- performance is >100x better than using an on-disk SQLite database. See https://github.com/rqlite/rqlite/blob/master/README.md#in-memory-databases

Since the rqlite Raft Consensus log is stored on disk, it's perfectly safe to use an in-memory database, since the SQLite database is completely rebuilt from the Raft log on startup (or after a crash). Still, I was hoping to support concurrent reads of an in-memory database. Concurrent writes of the database are never possible, as I understand it.

My testing passes if I set the parameters of the database pool such that there is only, ever, 1 connection available to the SQLite in-memory database. However, since (presumably) accessing an in-memory SQLite database is very fast, it probably doesn't matter in practice. And if users actually run a real rqlite cluster, the Raft subsystem is the real bottleneck (due to the back-and-forth cluster communications over the network), not the SQLite database.

Does this answer your question?

**Comment by rittneje** [comment]
Ah, I see. I didn't realize that in-memory was actually your predominant use case. It looks like your current plan is to force it to a single connection in the pool. In that case, please be sure to set all the following options:
- max idle time 0 (i.e., infinite)
- max lifetime 0 (i.e., infinite)
- max idle conns 1
- max open conns 1

That should prevent the single in-memory connection from ever getting closed.

**Comment by otoolep** [comment]
>It looks like your current plan is to force it to a single connection in the pool.

Not unless you have any other ideas that don't involve using a shared cache at this time. I may use a shared cache in the future, but I want a stable release that doesn't use it. But it sounds like you discourage shared cache, at least to start.

**Comment by rittneje** [comment]
> But it sounds like you discourage shared cache, at least to start.

To be clear, I discourage it because the SQLite authors themselves discourage it. However, until `vfs=memdb` was added in v3.36.0, there was no real alternative for in-memory databases.

Also, I did some testing.

1. Using `vfs=memdb`. Here, enabling WAL mode has no effect. It will operate the same as the standard rollback journal mode. Reads cannot happen concurrently with writes. Instead, the busy handler is invoked, which by default for this library will wait for up to 10 seconds before returning `SQLITE_BUSY`, but this is configurable via the `_busy_timeout` DSN option. Passing `mode=ro` will properly prevent that connection from writing to the database.
2. Using `mode=memory&cache=shared` without `sqlite_unlock_notify`. Here reads and writes against the same table cannot happen concurrently. If they do, then `SQLITE_LOCKED` is immediately returned. The busy handler will never be invoked. Since you cannot say both `mode=memory` and `mode=ro`, you need to use `PRAGMA query_only` instead, which can also be set automatically via the `_query_only` DSN option.
3. Using `mode=memory&cache=shared` with `sqlite_unlock_notify`. Again reads and writes against the same table cannot happen concurrently. If they do, then it will block potentially indefinitely. Even passing a `context.Context` to the database operation and canceling it will not save you. This appears to be a critical flaw in this library's use of `sqlite_unlock_notify` (and also perhaps SQLite's implementation of it) without a simple solution. Consequently, I do not recommend that anyone use the `sqlite_unlock_notify` build tag.

Given that, my recommendation to you would be to make two pools using `vfs=memdb`:
- read/write pool: `"file:/foobar.db?mode=rw&vfs=memdb&_txlock=immediate"`, `SetConnMaxIdleTime(0)`, `SetConnMaxLifetime(0)`, `SetMaxIdleConns(1)`, `SetMaxOpenConns(1)`
- read-only pool: `"file:/foobar.db?mode=ro&vfs=memdb&_txlock=deferred"`

If having two pools is not possible/feasible, then there are two options:
1. Create a single read/write "pool" with exactly one connection in it: `SetConnMaxIdleTime(0)`, `SetConnMaxLifetime(0)`, `SetMaxIdleConns(1)`, `SetMaxOpenConns(1)`. The choice of `_txlock` is not relevant. The choice of `mode=memory&cache=shared` vs. `vfs=memdb` is also not relevant. No concurrent operations will ever be performed. This is what you are currently doing.
2. Create a read/write pool configured as you like, with `_txlock=deferred`. Also create a dummy "pool" with exactly one connection to prevent the in-memory database from being released. You may observe sporadic `SQLITE_BUSY` or `SQLITE_LOCKED` errors, depending on whether you are using `vfs=memdb` or `mode=memory&cache=shared` and what kind of transactions are being performed.

**Comment by otoolep** [comment]
I tried your suggestion @rittneje and it works great! You can see the work-in-progress PR here: https://github.com/rqlite/rqlite/pull/842/files#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR108

Below is a graph showing Execute rate staying steady (green line) even as I increase query load (orange line). Previously Execute rate would drop as Query load would increase.

![ExecuteAndQueries](https://user-images.githubusercontent.com/536312/127776239-58f50b98-b24f-459b-a7dc-8fc05e833111.png)

This is a really great, thanks so much.
