### ISSUE TITLE
Error returned differently depending on connection-creation sequencing

### ISSUE THREAD

**Issue by otoolep** [mattn/go-sqlite3#966]
Demonstration code: https://gist.github.com/otoolep/9b08999a14401ce62ba0b1106a36f8b5

I see `QueryContext` sometimes return an error, and sometimes not, depending on when a connection is created. If a connection to a database is **created** before a table is deleted `SELECT * FROM foo` encounters an error during row scan, and `QueryContext` does not return an error. If the connection to the database is created **after** the table is deleted, `SELECT * FROM foo` error is returned by `QueryContext`.

Is this expected? If so, why?

```bash
$ ./simple 1
2021/08/04 09:01:30 rows.Err: no such table: foo
$ ./simple 2
2021/08/04 09:01:31 QueryContext2: no such table: foo
```

**Comment by otoolep** [comment]
I this issue while debugging unit test failures for https://github.com/rqlite/rqlite/pull/842 and reduced it to (I think) the demonstration code above.

**Comment by rittneje** [comment]
Does the issue also happen if you use a normal database file instead of memdb?

My guess is that SQLite is reading the original database schema at some point during the initial connection creation. In the first case, that was before the table was dropped, so it doesn't notice the problem until `sqlite3_step` runs. Meanwhile, in the second case, the original schema already didn't have the table, so `sqlite3_prepare_v2` itself fails.

I'd be curious to see the results for the reverse situation - a table that gets added after the connection is created.

Also, as an unrelated side note, you should add `_fk=1` to the DSN in your production code if you intend to use foreign keys, as SQLite does not enforce them by default.

**Comment by otoolep** [comment]
Yes, happens with on-disk too: https://gist.github.com/otoolep/3b495661353f9e9be5230531aaff6b27

**Comment by otoolep** [comment]
The reason I care about the difference is that the different behavior changes what rqlite HTTP API returns, and I don't want to change the API since that would be a breaking change. I can always work around this issue by modifying the API response to ensure it's the same as previous releases.

**Comment by otoolep** [comment]
@rittneje -- I'm ok with closing this issue. My main concern was that I might have a bug in my code, but since I can reproduce in a simple example, maybe it's just the way SQLite works. I'm sure if we dug into the SQLite code itself we'd learn for sure. I can code around it.

I wonder if it's related to https://www.sqlite.org/c3ref/table_column_metadata.html, which implies some metadata associated with each connection. 

_This function causes all database schemas to be read from disk and parsed, if that has not already been done, and returns an error if any errors are encountered while loading the schema._
