### ISSUE TITLE
*time.Time of struct is nil , but sqlite3 don't ignore when insert into db

### ISSUE THREAD

**Issue by GuoYHang** [mattn/go-sqlite3#988]
`
create table city_model (
    id integer primary key autoincrement,
    city_id integer,
    city_name char(255),
    dt date,
    create_time timestamp default current_timestamp
);

type CityModel struct {
   Id int `gorm:"column:id;type:int"`
   CityId int `gorm:"column:city_id;type:int"`
   CityName string `gorm:"column:city_name;type:varchar(255)"`,
   Dt time.Time `gorm:"colum:dt;type:date"`,
   CreateTime *time.Time `gorm:"column:create_time;type:timestamp"
}
`
Sqlite3 was linked with Gorm, but create_Time was not assigned during the Insert, causing the database Create_Time to become nil.
i think if the field is ptr and value of the field is nil, create_time should be current_timestamp

**Comment by rittneje** [comment]
SQLite itself does not work the way you want, partially because of how gorm apparently behaves.

If you explicitly tell SQLite to insert `NULL` then it will do so. It will not choose to insert the default value instead. If you want to use the default then you need to omit the column in question.
It seems gorm lacks a mechanism akin to `omitempty`, so it is always sending an explicit `NULL` to the `INSERT`.

Regardless, as per the gorm docs I think you are looking for the `autoCreateTime` field tag. https://gorm.io/docs/models.html#Fields-Tags
